version: '3.9'

networks:
  laravel-net:
    driver: bridge
  laravel-net-db:
    driver: bridge

services:

  api_redis:
    container_name: api_redis
    image: redis:alpine
    restart: always
    volumes:
      - vol_api_redis:/data
    networks:
      - laravel-net-db

  api_db:
    container_name: api_db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    user: 999:999
    ports:
      - "5432:5432"
    volumes:
      - vol_api_pgdata:/var/lib/postgresql/data
      - vol_api_pglog:/var/log/postgresql
    networks:
      - laravel-net-db

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.api.${ENV_TYPE}
    volumes:
      - .docker/build.sh:/var/www/build.sh
      - ./api:/var/www
      - vol_api_laravel-php-logs:/var/log/php
    depends_on:
      - api_db
      - api_redis
    networks:
      - laravel-net
      - laravel-net-db
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    expose:
      - "9000"
    command: sh /build.sh

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - vol_api_laravel-nginx-logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - laravel-net

volumes:
  vol_api_redis:
    driver: local
    driver_opts:
      type: none
      device: ./data/${ENV_TYPE}/logs/redis
      o: bind
  vol_api_pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./data/${ENV_TYPE}/pg
      o: bind
  vol_api_pglog:
    driver: local
    driver_opts:
      type: none
      device: ./data/${ENV_TYPE}/logs/postgres
      o: bind
  vol_api_laravel-php-logs:
    driver: local
    driver_opts:
      type: none
      device: ./data/${ENV_TYPE}/logs/php
      o: bind
  vol_api_laravel-nginx-logs:
    driver: local
    driver_opts:
      type: none
      device: ./data/${ENV_TYPE}/logs/nginx
      o: bind
